apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "penny-auction-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "penny-auction-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- with .Values.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "penny-auction-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "penny-auction-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
        - name: penny-auction-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}